baseUrl = "//jelmerderonde.github.io/ester/"

[menu]
  [[menu.main]]
  identifier = "sieraden"
  name       = "sieraden"
  url        = "/"
  weight     = 1

  [[menu.main]]
  identifier = "ander-werk"
  name       = "ander werk"
  url        = "/ander-werk/"
  weight     = 2

  [[menu.main]]
  identifier = "logo"
  name       = "logo"
  url        = "/"
  weight     = 3

  [[menu.main]]
  identifier = "contact"
  name       = "contact"
  url        = "/contact/"
  weight     = 4
