---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/product
  label: Product
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: none
  match: "*"
upload_dir: static/uploads
public_path: "/ester/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:/:year:/:month:/:day:"
version: 0.47.1
